name: Jira automation(Go to In Validate)

on:
  pull_request:
    types: [closed]
  

jobs:
    transition-issue:
      if: github.event.pull_request.merged == true
      name: Transition issue
      runs-on: ubuntu-latest
      steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}


      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{github.event.pull_request.head.ref}}
          transition: "Close Issue"
